title: Space Chem - a visual programming game
description: Everything you need to know if you want to beat SpaceChem
theme: just-the-docs

url: https://makwojwwa.github.io/SpaceChem

aux_links:
  Template Repository: https://github.com/makwojwwa/SpaceChem
